{{- if (.Values.service.enable) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.werf.name }}
spec:
  selector:
    app: {{ .Values.global.werf.name }}
  type: ClusterIP
  ports:
  {{- range $value := .Values.service.ports }}
  - name: {{ $value.name }}
    port: {{ $value.ServicePort }}
    targetPort: {{ $value.PodPort }}
    protocol: {{ $value.Protocol }}
  {{- end }}
{{ end }}
