{{- if (ne .Values.deployment.MinReplicas .Values.deployment.MaxReplicas) }}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.global.werf.name }}.autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.global.werf.name }}.deployment
  minReplicas: {{ .Values.deployment.MinReplicas }}
  maxReplicas: {{ .Values.deployment.MaxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
#status:
#  observedGeneration: 1
#  lastScaleTime: 10
#  currentReplicas: 1
#  desiredReplicas: 1
#  currentMetrics:
#  - type: Resource
#    resource:
#      name: cpu
#      current:
#        averageUtilization: 0
#        averageValue: 0
{{- end}}
